@startuml
!theme amiga

[*] --> NEW

state new_choice <<choice>>

NEW --> new_choice

new_choice --> WAITING_LIST : spots_free = 0
new_choice --> AWAITING_PAYMENT : spots_free > 0
new_choice --> PARTNER_SIGNUP : partner_name != ""

PARTNER_SIGNUP --> AWAITING_PAYMENT : Partner confirmed
PARTNER_SIGNUP --> CANCELLED : Manual state change

WAITING_LIST --> new_choice : on_change

WAITING_LIST --> CANCELLED : Cancellation requested

AWAITING_PAYMENT --> CANCELLED : Payment not received within 24 h

AWAITING_PAYMENT --> CONFIRMED : Payment received

state CONFIRMED {

}


@enduml
